site_name: HBCD Data Release
theme: readthedocs
extra_css:
  - css/custom.css

plugins:
  - search

docs_dir: docs

nav: 
  - ABOUT: index.md
  - HOW TO ACCESS DATA: data_access.md
  - DUC PROCESS: duc_process.md
  - FAQS: faq.md
  - CONTACT: contact.md
  - RESPONSIBLE DATA USE: resp_data_use.md
  - DATA DICTIONARY EXPLORER: datadictionary.md
  - Release Notes:
      - "Data Measures & Quality Control":
          - Demographics: measures/demographics.md
          - "Social & Environmental Determinants":
              - Neighborhood Safety: measures/socenv_determinants/neighborhood_safety.md
              - Discrimination: measures/socenv_determinants/discrimination.md
              - PACES: measures/socenv_determinants/PACES.md
              - PROMIS: measures/socenv_determinants/perceived_stress.md
              - Baby's First Years: measures/socenv_determinants/bfy.md
              - eHITS: measures/socenv_determinants/eHITS.md
              - Other: measures/socenv_determinants/other.md
          - "Neurocognition & Language": 
              - Multilingual Language Development Screener: measures/neurocog_language.md          
          - Electroencephalogram (EEG): 
              - Common Measure Details: measures/eeg/measures_all.md
              - Video Resting State: measures/eeg/video_rs.md
              - Faces Task: measures/eeg/faces_task.md
              - Auditory Mismatch Negativity Task: measures/eeg/aud_mm.md
              - Visual Evoked Potential Task: measures/eeg/vis_ep_task.md
          - Magnetic Resonance Imaging (MRI):
              - Common Measure Details: measures/mri/mri_measures_all.md
              - Structural MRI: measures/mri/smri.md
              - Functional MRI: measures/mri/fmri.md
              - Diffusion MRI: measures/mri/dmri.md
              - Quantitative MRI: measures/mri/qalas.md
              - Magnetic Resonance Spectroscopy: measures/mri/mrs.md
          - "Novel Technologies & Wearable Sensors": 
              - Wearable Sensors: measures/sensors/wearable_sensors.md
              - Infant Sensor Questionnaire: measures/sensors/sensor_questionnaire.md
          - "Physical Health": 
              - Food Insecurity: measures/physhealth/food_insecurity.md
              - Breastfeeding: measures/physhealth/breastfeeding.md
              - Growth: measures/physhealth/growth.md
              - Other: measures/physhealth/other.md
          - "Behavior & Caregiver-Child Interaction": 
              - IBQ-R (VSF)+BI: measures/beh_CG_interaction/IBQ-R.md
              - MAPS-TL: measures/beh_CG_interaction/MAPS-TL.md
              - ecPROMIS: measures/beh_CG_interaction/ePROMIS.md
              - Other: measures/beh_CG_interaction/other.md
          - "Pregnancy & Exposure": 
              - Pregnancy Health Measures (7): measures/pregexp/preghealth_all.md
              - Infant Health: measures/pregexp/infanthealth.md
              - "Personal & Family Psychiatric History": measures/pregexp/psych_history.md
              - Substance Use Measures (4): measures/pregexp/substanceuse_all.md
              - Mental Health: measures/pregexp/mentalhealth.md
              - DSM5 PTSD/short stress scale: measures/pregexp/NSESSS.md
              - EPDS: measures/pregexp/edinburgh_postnatal_depression.md
      - "MRI Protocols": 
          - Overview: mriprotocols/overview.md
          - Siemens: mriprotocols/siemens.md
          - GE: mriprotocols/ge.md
          - Philips: mriprotocols/philips.md
      - BIDS Dataset:
          - Overview: datacuration/bids.md
          - Imaging: datacuration/imaging.md
          - EEG: datacuration/eeg.md
          - Motion Data: datacuration/motion.md
          - Phenotypes: datacuration/phenotypes.md
      - Data Processing: 
          - Pipelines: processing/pipelines.md
          - Pipeline Software Standards: processing/standards.md
          - External Processing Documentation: processing/processing.md
  - Change Log: 
      - Pending Updates: changelog/pending.md
      - Version History: 
          - Beta Release 5/V1.4: changelog/versions/v1.4.md
          - Beta Release 4/V1.3: changelog/versions/v1.3.md
          - Beta Release 3/V1.2: changelog/versions/v1.2.md
          - Beta Release 2/V1.1: changelog/versions/v1.1.md
          - Beta Release 1/V1.0: changelog/versions/v1.0.md
